export const teams = [
  { id: 'morocco', name: 'Morocco', code: 'MAR', colors: ['#d71920', '#087a4a'], logo: '/team-logos/morocco.png' },
  { id: 'france', name: 'France', code: 'FRA', colors: ['#133a8a', '#e62b3a'], logo: '/team-logos/france.png' },
  { id: 'brazil', name: 'Brazil', code: 'BRA', colors: ['#f5d22e', '#16834b'], logo: '/team-logos/brazil.svg' },
  { id: 'argentina', name: 'Argentina', code: 'ARG', colors: ['#75b9e7', '#ffffff'], logo: '/team-logos/argentina.svg' },
  { id: 'portugal', name: 'Portugal', code: 'POR', colors: ['#ce1733', '#13874b'], logo: '/team-logos/portugal.svg' },
  { id: 'spain', name: 'Spain', code: 'ESP', colors: ['#df2638', '#f5c62c'], logo: '/team-logos/spain.svg' },
  { id: 'england', name: 'England', code: 'ENG', colors: ['#f4f4f2', '#d51d36'], logo: '/team-logos/england.svg' },
  { id: 'germany', name: 'Germany', code: 'GER', colors: ['#171717', '#d7aa34'], logo: '/team-logos/germany.svg' },
  { id: 'italy', name: 'Italy', code: 'ITA', colors: ['#1765ab', '#ffffff'], logo: '/team-logos/italy.svg' },
  { id: 'senegal', name: 'Senegal', code: 'SEN', colors: ['#16804f', '#f0c72e'], logo: '/team-logos/senegal.png' },
  { id: 'algeria', name: 'Algeria', code: 'ALG', colors: ['#16864c', '#ffffff'], logo: '/team-logos/algeria.png' },
  { id: 'egypt', name: 'Egypt', code: 'EGY', colors: ['#cf202f', '#111111'], logo: '/team-logos/egypt.png' },
  { id: 'nigeria', name: 'Nigeria', code: 'NGA', colors: ['#12864b', '#ffffff'], logo: '/team-logos/nigeria.png' },
  { id: 'japan', name: 'Japan', code: 'JPN', colors: ['#173a8f', '#d51e3b'], logo: '/team-logos/japan.png' },
  { id: 'south-korea', name: 'South Korea', code: 'KOR', colors: ['#d9233f', '#173d85'], logo: '/team-logos/south-korea.png' },
  { id: 'mexico', name: 'Mexico', code: 'MEX', colors: ['#087b4b', '#d62435'], logo: '/team-logos/mexico.png' },
  { id: 'usa', name: 'United States', code: 'USA', colors: ['#203e83', '#d3283e'], logo: '/team-logos/usa.png' },
  { id: 'netherlands', name: 'Netherlands', code: 'NED', colors: ['#f36d21', '#173c87'], logo: '/team-logos/netherlands.png' },
  { id: 'belgium', name: 'Belgium', code: 'BEL', colors: ['#171717', '#d82735'], logo: '/team-logos/belgium.png' },
  { id: 'croatia', name: 'Croatia', code: 'CRO', colors: ['#d61f35', '#ffffff'], logo: '/team-logos/croatia.png' },
];

const jerseyByTeam = {
  morocco: '/jerseys/morocco-home.png',
  france: '/jerseys/france-home.jpg',
  brazil: '/jerseys/brazil-home.png',
  argentina: '/jerseys/argentina-home.jpg',
  portugal: '/jerseys/portugal-home.png',
  spain: '/jerseys/spain-home.png',
  england: '/jerseys/england-home.jpg',
  germany: '/jerseys/germany-home.png',
  italy: '/jerseys/italy-home.png',
  senegal: '/jerseys/senegal-home.png',
  algeria: '/jerseys/algeria-home.png',
  egypt: '/jerseys/egypt-home.png',
  nigeria: '/jerseys/nigeria-home.png',
  japan: '/jerseys/japan-home.jpg',
  'south-korea': '/jerseys/south-korea-home.jpg',
  mexico: '/jerseys/mexico-home.png',
  usa: '/jerseys/usa-home.png',
  netherlands: '/jerseys/netherlands-home.png',
  belgium: '/jerseys/belgium-home.png',
  croatia: '/jerseys/croatia-home.png',
};

export const jerseyBackByTeam = {
  morocco: '/jerseys-back-transparent/morocco-back.png',
  france: '/jerseys-back-transparent/france-back.png',
  brazil: '/jerseys-back-transparent/brazil-back.png',
  argentina: '/jerseys-back-transparent/argentina-back.png',
  portugal: '/jerseys-back-transparent/portugal-back.png',
  spain: '/jerseys-back-transparent/spain-back.png',
  england: '/jerseys-back-transparent/england-back.png',
  germany: '/jerseys-back-transparent/germany-back.png',
  italy: '/jerseys-back-transparent/italy-back.png',
  senegal: '/jerseys-back-transparent/senegal-back.png',
  algeria: '/jerseys-back-transparent/algeria-back.png',
  egypt: '/jerseys-back-transparent/egypt-back.png',
  nigeria: '/jerseys-back-transparent/nigeria-back.png',
  japan: '/jerseys-back-transparent/japan-back.png',
  'south-korea': '/jerseys-back-transparent/south-korea-back.png',
  mexico: '/jerseys-back-transparent/mexico-back.png',
  usa: '/jerseys-back-transparent/usa-back.png',
  netherlands: '/jerseys-back-transparent/netherlands-back.png',
  belgium: '/jerseys-back-transparent/belgium-back.png',
  croatia: '/jerseys-back-transparent/croatia-back.png',
};

export const jerseyPrintByTeam = {
  morocco: { top: '29.4%', width: '36%', color: '#f6f2e8', outline: 'rgba(24, 24, 24, .78)' },
  france: { top: '29.2%', width: '35%', color: '#f7f7f5', outline: 'rgba(15, 25, 57, .85)' },
  brazil: { top: '29.8%', width: '35%', color: '#11181a', outline: 'rgba(255, 255, 255, .7)' },
  argentina: { top: '30.2%', width: '34%', color: '#121416', outline: 'rgba(255, 255, 255, .74)' },
  portugal: { top: '31.2%', width: '35%', color: '#f6f4ee', outline: 'rgba(19, 21, 21, .82)' },
  spain: { top: '30.4%', width: '35%', color: '#f6d14c', outline: 'rgba(110, 14, 22, .88)' },
  england: { top: '30%', width: '34%', color: '#b22b3a', outline: 'rgba(20, 28, 47, .82)' },
  germany: { top: '30%', width: '34%', color: '#171816', outline: 'rgba(245, 241, 225, .72)' },
  italy: { top: '29.6%', width: '35%', color: '#f4f6fb', outline: 'rgba(15, 67, 150, .88)' },
  senegal: { top: '29.5%', width: '35%', color: '#171816', outline: 'rgba(255, 255, 255, .72)' },
  algeria: { top: '30.3%', width: '35%', color: '#171816', outline: 'rgba(255, 255, 255, .72)' },
  egypt: { top: '29.7%', width: '35%', color: '#f6f4ef', outline: 'rgba(18, 18, 18, .84)' },
  nigeria: { top: '29.9%', width: '35%', color: '#f6f4ef', outline: 'rgba(16, 24, 20, .82)' },
  japan: { top: '29.3%', width: '34%', color: '#f6f5f1', outline: 'rgba(12, 20, 41, .84)' },
  'south-korea': { top: '29.1%', width: '34%', color: '#171816', outline: 'rgba(255, 255, 255, .7)' },
  mexico: { top: '29.6%', width: '37%', color: '#132316', outline: 'rgba(255, 255, 255, .64)' },
  usa: { top: '29.5%', width: '35%', color: '#171816', outline: 'rgba(255, 255, 255, .72)' },
  netherlands: { top: '29.8%', width: '34%', color: '#101417', outline: 'rgba(255, 157, 82, .76)' },
  belgium: { top: '29.6%', width: '35%', color: '#f3efe6', outline: 'rgba(18, 18, 18, .86)' },
  croatia: { top: '30.6%', width: '35%', color: '#171816', outline: 'rgba(255, 255, 255, .72)' },
};

const photos = {
  shoes: [
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',
    'https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=900&q=85',
  ],
  sandals: [
    'https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=900&q=85',
  ],
};

export const products = teams.flatMap((team, teamIndex) => [
  {
    id: `${team.id}-home`,
    teamId: team.id,
    category: 'Jerseys',
    name: `${team.name} Home Jersey 2026`,
    price: 89,
    oldPrice: 110,
    image: jerseyByTeam[team.id],
    badge: teamIndex % 3 === 0 ? 'Bestseller' : 'New',
    color: team.colors[0],
  },
  {
    id: `${team.id}-away`,
    teamId: team.id,
    category: 'Jerseys',
    name: `${team.name} Supporter Jersey 2026`,
    price: 84,
    image: jerseyByTeam[team.id],
    color: team.colors[1],
  },
  {
    id: `${team.id}-slides`,
    teamId: team.id,
    category: 'Sandals',
    name: `${team.name} Crest Slides`,
    price: 39,
    image: photos.sandals[0],
    color: team.colors[0],
  },
  {
    id: `${team.id}-shoes`,
    teamId: team.id,
    category: 'Shoes',
    name: `${team.name} Street Trainers`,
    price: 115,
    oldPrice: teamIndex % 2 === 0 ? 135 : null,
    image: photos.shoes[teamIndex % photos.shoes.length],
    badge: teamIndex % 2 === 0 ? 'Limited' : null,
    color: team.colors[0],
  },
]);
