export const importedTracksuits = [
  {
    "id": "tracksuit-brazil",
    "teamId": "brazil",
    "category": "Survette",
    "name": "Brazil Yellow Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-brazil-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-brazil-primary.webp",
      "/products/tracksuits/tracksuit-brazil-01.webp",
      "/products/tracksuits/tracksuit-brazil-02.webp",
      "/products/tracksuits/tracksuit-brazil-03.webp",
      "/products/tracksuits/tracksuit-brazil-04.webp",
      "/products/tracksuits/tracksuit-brazil-05.webp",
      "/products/tracksuits/tracksuit-brazil-06.webp",
      "/products/tracksuits/tracksuit-brazil-07.webp",
      "/products/tracksuits/tracksuit-brazil-08.webp"
    ],
    "badge": "New",
    "color": "#f5d22e",
    "description": "2026世界杯巴西黄色出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/239572083?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-brazil-1",
    "teamId": "brazil",
    "category": "Survette",
    "name": "Brazil Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-brazil-1-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-brazil-1-primary.webp",
      "/products/tracksuits/tracksuit-brazil-1-01.webp",
      "/products/tracksuits/tracksuit-brazil-1-02.webp",
      "/products/tracksuits/tracksuit-brazil-1-03.webp",
      "/products/tracksuits/tracksuit-brazil-1-04.webp",
      "/products/tracksuits/tracksuit-brazil-1-05.webp",
      "/products/tracksuits/tracksuit-brazil-1-06.webp",
      "/products/tracksuits/tracksuit-brazil-1-07.webp"
    ],
    "badge": "New",
    "color": "#f5d22e",
    "description": "2026世界杯巴西出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/232516536?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-c2604-argentina-royal-blue-trousers",
    "teamId": "argentina",
    "category": "Survette",
    "name": "Argentina Royal Blue Tracksuit 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-primary.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-01.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-02.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-03.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-04.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-05.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-06.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-07.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-08.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-09.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-10.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-11.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-12.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-13.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-14.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-15.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-16.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-17.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-18.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-19.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-20.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-21.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-22.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-23.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-24.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-25.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-26.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-27.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-28.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-29.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-30.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-31.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-32.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-33.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-34.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-35.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-36.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-37.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-38.webp",
      "/products/tracksuits/tracksuit-c2604-argentina-royal-blue-trousers-39.webp"
    ],
    "badge": "New",
    "color": "#75b9e7",
    "description": "C2604阿根廷宝蓝色 长裤套装",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/236007372?uid=1"
  },
  {
    "id": "tracksuit-england",
    "teamId": "england",
    "category": "Survette",
    "name": "England Green Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-england-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-england-primary.webp",
      "/products/tracksuits/tracksuit-england-01.webp",
      "/products/tracksuits/tracksuit-england-02.webp",
      "/products/tracksuits/tracksuit-england-03.webp",
      "/products/tracksuits/tracksuit-england-04.webp",
      "/products/tracksuits/tracksuit-england-05.webp",
      "/products/tracksuits/tracksuit-england-06.webp",
      "/products/tracksuits/tracksuit-england-07.webp",
      "/products/tracksuits/tracksuit-england-08.webp"
    ],
    "badge": "New",
    "color": "#f4f4f2",
    "description": "2026世界杯英格兰上青色出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/239889920?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-england-1",
    "teamId": "england",
    "category": "Survette",
    "name": "England Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-england-1-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-england-1-primary.webp",
      "/products/tracksuits/tracksuit-england-1-01.webp",
      "/products/tracksuits/tracksuit-england-1-02.webp",
      "/products/tracksuits/tracksuit-england-1-03.webp",
      "/products/tracksuits/tracksuit-england-1-04.webp",
      "/products/tracksuits/tracksuit-england-1-05.webp",
      "/products/tracksuits/tracksuit-england-1-06.webp",
      "/products/tracksuits/tracksuit-england-1-07.webp",
      "/products/tracksuits/tracksuit-england-1-08.webp",
      "/products/tracksuits/tracksuit-england-1-09.webp"
    ],
    "badge": "New",
    "color": "#f4f4f2",
    "description": "2026世界杯英格兰出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/232516335?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-france",
    "teamId": "france",
    "category": "Survette",
    "name": "France Dark Blue Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-france-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-france-primary.webp",
      "/products/tracksuits/tracksuit-france-01.webp",
      "/products/tracksuits/tracksuit-france-02.webp",
      "/products/tracksuits/tracksuit-france-03.webp",
      "/products/tracksuits/tracksuit-france-04.webp",
      "/products/tracksuits/tracksuit-france-05.webp",
      "/products/tracksuits/tracksuit-france-06.webp"
    ],
    "badge": "New",
    "color": "#133a8a",
    "description": "2026世界杯法国出场服带帽深蓝色S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/235916933?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-france-1",
    "teamId": "france",
    "category": "Survette",
    "name": "France Light Blue Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-france-1-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-france-1-primary.webp",
      "/products/tracksuits/tracksuit-france-1-01.webp",
      "/products/tracksuits/tracksuit-france-1-02.webp",
      "/products/tracksuits/tracksuit-france-1-03.webp",
      "/products/tracksuits/tracksuit-france-1-04.webp",
      "/products/tracksuits/tracksuit-france-1-05.webp",
      "/products/tracksuits/tracksuit-france-1-06.webp",
      "/products/tracksuits/tracksuit-france-1-07.webp",
      "/products/tracksuits/tracksuit-france-1-08.webp"
    ],
    "badge": null,
    "color": "#133a8a",
    "description": "2026世界杯法国出场服带帽浅蓝色S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/235916804?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-netherlands",
    "teamId": "netherlands",
    "category": "Survette",
    "name": "Netherlands Orange Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-netherlands-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-netherlands-primary.webp",
      "/products/tracksuits/tracksuit-netherlands-01.webp",
      "/products/tracksuits/tracksuit-netherlands-02.webp",
      "/products/tracksuits/tracksuit-netherlands-03.webp",
      "/products/tracksuits/tracksuit-netherlands-04.webp",
      "/products/tracksuits/tracksuit-netherlands-05.webp",
      "/products/tracksuits/tracksuit-netherlands-06.webp",
      "/products/tracksuits/tracksuit-netherlands-07.webp",
      "/products/tracksuits/tracksuit-netherlands-08.webp"
    ],
    "badge": null,
    "color": "#f36d21",
    "description": "2026世界杯荷兰橙色出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/239890191?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-nigeria",
    "teamId": "nigeria",
    "category": "Survette",
    "name": "Nigeria Green Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-nigeria-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-nigeria-primary.webp",
      "/products/tracksuits/tracksuit-nigeria-01.webp",
      "/products/tracksuits/tracksuit-nigeria-02.webp",
      "/products/tracksuits/tracksuit-nigeria-03.webp",
      "/products/tracksuits/tracksuit-nigeria-04.webp",
      "/products/tracksuits/tracksuit-nigeria-05.webp",
      "/products/tracksuits/tracksuit-nigeria-06.webp",
      "/products/tracksuits/tracksuit-nigeria-07.webp",
      "/products/tracksuits/tracksuit-nigeria-08.webp"
    ],
    "badge": null,
    "color": "#12864b",
    "description": "2026世界杯尼日利亚绿色出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/240034116?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-norway",
    "teamId": "norway",
    "category": "Survette",
    "name": "Norway Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-norway-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-norway-primary.webp",
      "/products/tracksuits/tracksuit-norway-01.webp",
      "/products/tracksuits/tracksuit-norway-02.webp",
      "/products/tracksuits/tracksuit-norway-03.webp",
      "/products/tracksuits/tracksuit-norway-04.webp",
      "/products/tracksuits/tracksuit-norway-05.webp",
      "/products/tracksuits/tracksuit-norway-06.webp",
      "/products/tracksuits/tracksuit-norway-07.webp",
      "/products/tracksuits/tracksuit-norway-08.webp"
    ],
    "badge": null,
    "color": "#ba0c2f",
    "description": "2026世界杯挪威出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/239890592?uid=1&isSubCate=false&referrercate=5187577"
  },
  {
    "id": "tracksuit-usa",
    "teamId": "usa",
    "category": "Survette",
    "name": "USA Red Match Hoodie 2026",
    "price": 119,
    "oldPrice": null,
    "image": "/products/tracksuits/tracksuit-usa-primary.webp",
    "gallery": [
      "/products/tracksuits/tracksuit-usa-primary.webp",
      "/products/tracksuits/tracksuit-usa-01.webp",
      "/products/tracksuits/tracksuit-usa-02.webp",
      "/products/tracksuits/tracksuit-usa-03.webp",
      "/products/tracksuits/tracksuit-usa-04.webp",
      "/products/tracksuits/tracksuit-usa-05.webp",
      "/products/tracksuits/tracksuit-usa-06.webp",
      "/products/tracksuits/tracksuit-usa-07.webp",
      "/products/tracksuits/tracksuit-usa-08.webp"
    ],
    "badge": null,
    "color": "#203e83",
    "description": "2026世界杯美国队红色出场服带帽S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/240034090?uid=1&isSubCate=false&referrercate=5187577"
  }
];
