export const importedProducts = [
  {
    "id": "imported-argentina",
    "teamId": "argentina",
    "category": "Jerseys",
    "name": "Argentina Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-argentina-primary.webp",
    "gallery": [
      "/products/imported-argentina-primary.webp",
      "/products/imported-argentina-01.webp",
      "/products/imported-argentina-02.webp",
      "/products/imported-argentina-03.webp",
      "/products/imported-argentina-04.webp",
      "/products/imported-argentina-05.webp",
      "/products/imported-argentina-06.webp",
      "/products/imported-argentina-07.webp",
      "/products/imported-argentina-08.webp",
      "/products/imported-argentina-09.webp",
      "/products/imported-argentina-10.webp",
      "/products/imported-argentina-11.webp",
      "/products/imported-argentina-12.webp"
    ],
    "badge": "New",
    "color": "#75b9e7",
    "description": "2026阿根廷客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/230702528?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  },
  {
    "id": "imported-belgium",
    "teamId": "belgium",
    "category": "Jerseys",
    "name": "Belgium Home Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-belgium-primary.webp",
    "gallery": [
      "/products/imported-belgium-primary.webp",
      "/products/imported-belgium-01.webp",
      "/products/imported-belgium-02.webp",
      "/products/imported-belgium-03.webp",
      "/products/imported-belgium-04.webp",
      "/products/imported-belgium-05.webp",
      "/products/imported-belgium-06.webp",
      "/products/imported-belgium-07.webp",
      "/products/imported-belgium-08.webp",
      "/products/imported-belgium-09.webp",
      "/products/imported-belgium-10.webp"
    ],
    "badge": "New",
    "color": "#171717",
    "description": "2026比利时主场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/213443719?uid=1"
  },
  {
    "id": "imported-brazil",
    "teamId": "brazil",
    "category": "Jerseys",
    "name": "Brazil Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-brazil-primary.webp",
    "gallery": [
      "/products/imported-brazil-primary.webp",
      "/products/imported-brazil-01.webp",
      "/products/imported-brazil-02.webp",
      "/products/imported-brazil-03.webp",
      "/products/imported-brazil-04.webp",
      "/products/imported-brazil-05.webp",
      "/products/imported-brazil-06.webp",
      "/products/imported-brazil-07.webp",
      "/products/imported-brazil-08.webp",
      "/products/imported-brazil-09.webp",
      "/products/imported-brazil-10.webp"
    ],
    "badge": "New",
    "color": "#f5d22e",
    "description": "2026巴西客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/230119090?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  },
  {
    "id": "imported-brazil-1",
    "teamId": "brazil",
    "category": "Jerseys",
    "name": "Brazil Kids Jersey 2026",
    "price": 74,
    "oldPrice": null,
    "image": "/products/imported-brazil-1-primary.webp",
    "gallery": [
      "/products/imported-brazil-1-primary.webp",
      "/products/imported-brazil-1-01.webp",
      "/products/imported-brazil-1-02.webp",
      "/products/imported-brazil-1-03.webp",
      "/products/imported-brazil-1-04.webp",
      "/products/imported-brazil-1-05.webp",
      "/products/imported-brazil-1-06.webp",
      "/products/imported-brazil-1-07.webp"
    ],
    "badge": "New",
    "color": "#f5d22e",
    "description": "2026巴西主场 童装",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/233911842?uid=1&isSubCate=false&referrercate=4511234&utm_source=copyLink"
  },
  {
    "id": "imported-croatia-s-2xl",
    "teamId": "croatia",
    "category": "Jerseys",
    "name": "Croatia Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-croatia-s-2xl-primary.webp",
    "gallery": [
      "/products/imported-croatia-s-2xl-primary.webp",
      "/products/imported-croatia-s-2xl-01.webp",
      "/products/imported-croatia-s-2xl-02.webp",
      "/products/imported-croatia-s-2xl-03.webp",
      "/products/imported-croatia-s-2xl-04.webp",
      "/products/imported-croatia-s-2xl-05.webp",
      "/products/imported-croatia-s-2xl-06.webp",
      "/products/imported-croatia-s-2xl-07.webp"
    ],
    "badge": "New",
    "color": "#d61f35",
    "description": "2026克罗地亚客场S~2XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/235942613?uid=1"
  },
  {
    "id": "imported-croatia-s-2xl-1",
    "teamId": "croatia",
    "category": "Jerseys",
    "name": "Croatia Home Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-croatia-s-2xl-1-primary.webp",
    "gallery": [
      "/products/imported-croatia-s-2xl-1-primary.webp",
      "/products/imported-croatia-s-2xl-1-01.webp",
      "/products/imported-croatia-s-2xl-1-02.webp",
      "/products/imported-croatia-s-2xl-1-03.webp",
      "/products/imported-croatia-s-2xl-1-04.webp",
      "/products/imported-croatia-s-2xl-1-05.webp",
      "/products/imported-croatia-s-2xl-1-06.webp",
      "/products/imported-croatia-s-2xl-1-07.webp"
    ],
    "badge": "New",
    "color": "#d61f35",
    "description": "2026克罗地亚主场S~2XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/235217817?uid=1"
  },
  {
    "id": "imported-d2603-german-white-half-pull",
    "teamId": "germany",
    "category": "Jerseys",
    "name": "Germany White Half-Zip Training Top",
    "price": 94,
    "oldPrice": null,
    "image": "/products/imported-d2603-german-white-half-pull-primary.webp",
    "gallery": [
      "/products/imported-d2603-german-white-half-pull-primary.webp",
      "/products/imported-d2603-german-white-half-pull-01.webp",
      "/products/imported-d2603-german-white-half-pull-02.webp",
      "/products/imported-d2603-german-white-half-pull-03.webp",
      "/products/imported-d2603-german-white-half-pull-04.webp",
      "/products/imported-d2603-german-white-half-pull-05.webp",
      "/products/imported-d2603-german-white-half-pull-06.webp",
      "/products/imported-d2603-german-white-half-pull-07.webp",
      "/products/imported-d2603-german-white-half-pull-08.webp",
      "/products/imported-d2603-german-white-half-pull-09.webp",
      "/products/imported-d2603-german-white-half-pull-10.webp",
      "/products/imported-d2603-german-white-half-pull-11.webp",
      "/products/imported-d2603-german-white-half-pull-12.webp",
      "/products/imported-d2603-german-white-half-pull-13.webp",
      "/products/imported-d2603-german-white-half-pull-14.webp",
      "/products/imported-d2603-german-white-half-pull-15.webp",
      "/products/imported-d2603-german-white-half-pull-16.webp",
      "/products/imported-d2603-german-white-half-pull-17.webp",
      "/products/imported-d2603-german-white-half-pull-18.webp",
      "/products/imported-d2603-german-white-half-pull-19.webp",
      "/products/imported-d2603-german-white-half-pull-20.webp",
      "/products/imported-d2603-german-white-half-pull-21.webp",
      "/products/imported-d2603-german-white-half-pull-22.webp",
      "/products/imported-d2603-german-white-half-pull-23.webp",
      "/products/imported-d2603-german-white-half-pull-24.webp",
      "/products/imported-d2603-german-white-half-pull-25.webp",
      "/products/imported-d2603-german-white-half-pull-26.webp",
      "/products/imported-d2603-german-white-half-pull-27.webp",
      "/products/imported-d2603-german-white-half-pull-28.webp",
      "/products/imported-d2603-german-white-half-pull-29.webp",
      "/products/imported-d2603-german-white-half-pull-30.webp"
    ],
    "badge": "New",
    "color": "#171717",
    "description": "D2603 德国白色半拉",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/222939572?uid=1"
  },
  {
    "id": "imported-england",
    "teamId": "england",
    "category": "Jerseys",
    "name": "England Kids Jersey 2026",
    "price": 74,
    "oldPrice": null,
    "image": "/products/imported-england-primary.webp",
    "gallery": [
      "/products/imported-england-primary.webp",
      "/products/imported-england-01.webp",
      "/products/imported-england-02.webp",
      "/products/imported-england-03.webp",
      "/products/imported-england-04.webp",
      "/products/imported-england-05.webp"
    ],
    "badge": "New",
    "color": "#f4f4f2",
    "description": "2627英格兰客场 童装",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/233710790?uid=1"
  },
  {
    "id": "imported-england-1",
    "teamId": "england",
    "category": "Jerseys",
    "name": "England Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-england-1-primary.webp",
    "gallery": [
      "/products/imported-england-1-primary.webp",
      "/products/imported-england-1-01.webp",
      "/products/imported-england-1-02.webp",
      "/products/imported-england-1-03.webp",
      "/products/imported-england-1-04.webp",
      "/products/imported-england-1-05.webp",
      "/products/imported-england-1-06.webp",
      "/products/imported-england-1-07.webp",
      "/products/imported-england-1-08.webp"
    ],
    "badge": null,
    "color": "#f4f4f2",
    "description": "2627英格兰客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/227679478?uid=1"
  },
  {
    "id": "imported-france",
    "teamId": "france",
    "category": "Jerseys",
    "name": "France Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-france-primary.webp",
    "gallery": [
      "/products/imported-france-primary.webp",
      "/products/imported-france-01.webp",
      "/products/imported-france-02.webp",
      "/products/imported-france-03.webp",
      "/products/imported-france-04.webp",
      "/products/imported-france-05.webp",
      "/products/imported-france-06.webp",
      "/products/imported-france-07.webp",
      "/products/imported-france-08.webp",
      "/products/imported-france-09.webp"
    ],
    "badge": null,
    "color": "#133a8a",
    "description": "2627法国客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/228344197?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  },
  {
    "id": "imported-france-1",
    "teamId": "france",
    "category": "Jerseys",
    "name": "France Kids Jersey 2026",
    "price": 74,
    "oldPrice": null,
    "image": "/products/imported-france-1-primary.webp",
    "gallery": [
      "/products/imported-france-1-primary.webp",
      "/products/imported-france-1-01.webp",
      "/products/imported-france-1-02.webp",
      "/products/imported-france-1-03.webp",
      "/products/imported-france-1-04.webp",
      "/products/imported-france-1-05.webp"
    ],
    "badge": null,
    "color": "#133a8a",
    "description": "2627法国主场 童装",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/234991640?uid=1&isSubCate=false&referrercate=4511234&utm_source=copyLink"
  },
  {
    "id": "imported-germany",
    "teamId": "germany",
    "category": "Jerseys",
    "name": "Germany Kids Jersey 2026",
    "price": 74,
    "oldPrice": null,
    "image": "/products/imported-germany-primary.webp",
    "gallery": [
      "/products/imported-germany-primary.webp",
      "/products/imported-germany-01.webp",
      "/products/imported-germany-02.webp",
      "/products/imported-germany-03.webp",
      "/products/imported-germany-04.webp",
      "/products/imported-germany-05.webp",
      "/products/imported-germany-06.webp"
    ],
    "badge": null,
    "color": "#171717",
    "description": "2026德国主场童装",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/213915454?uid=1"
  },
  {
    "id": "imported-italy",
    "teamId": "italy",
    "category": "Jerseys",
    "name": "Italy Home Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-italy-primary.webp",
    "gallery": [
      "/products/imported-italy-primary.webp",
      "/products/imported-italy-01.webp",
      "/products/imported-italy-02.webp",
      "/products/imported-italy-03.webp",
      "/products/imported-italy-04.webp",
      "/products/imported-italy-05.webp",
      "/products/imported-italy-06.webp",
      "/products/imported-italy-07.webp",
      "/products/imported-italy-08.webp",
      "/products/imported-italy-09.webp",
      "/products/imported-italy-10.webp",
      "/products/imported-italy-11.webp",
      "/products/imported-italy-12.webp"
    ],
    "badge": null,
    "color": "#1765ab",
    "description": "2026意大利主场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/210030300?uid=1&isSubCate=false&referrercate=5063658"
  },
  {
    "id": "imported-italy-1",
    "teamId": "italy",
    "category": "Jerseys",
    "name": "Italy Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-italy-1-primary.webp",
    "gallery": [
      "/products/imported-italy-1-primary.webp",
      "/products/imported-italy-1-01.webp",
      "/products/imported-italy-1-02.webp",
      "/products/imported-italy-1-03.webp",
      "/products/imported-italy-1-04.webp",
      "/products/imported-italy-1-05.webp",
      "/products/imported-italy-1-06.webp",
      "/products/imported-italy-1-07.webp",
      "/products/imported-italy-1-08.webp",
      "/products/imported-italy-1-09.webp",
      "/products/imported-italy-1-10.webp",
      "/products/imported-italy-1-11.webp"
    ],
    "badge": null,
    "color": "#1765ab",
    "description": "2026意大利客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/213049788?uid=1&isSubCate=false&referrercate=5063658"
  },
  {
    "id": "imported-mexican-second-passenger",
    "teamId": "germany",
    "category": "Jerseys",
    "name": "Germany Third Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-mexican-second-passenger-primary.webp",
    "gallery": [
      "/products/imported-mexican-second-passenger-primary.webp",
      "/products/imported-mexican-second-passenger-01.webp",
      "/products/imported-mexican-second-passenger-02.webp",
      "/products/imported-mexican-second-passenger-03.webp",
      "/products/imported-mexican-second-passenger-04.webp",
      "/products/imported-mexican-second-passenger-05.webp",
      "/products/imported-mexican-second-passenger-06.webp",
      "/products/imported-mexican-second-passenger-07.webp",
      "/products/imported-mexican-second-passenger-08.webp",
      "/products/imported-mexican-second-passenger-09.webp",
      "/products/imported-mexican-second-passenger-10.webp",
      "/products/imported-mexican-second-passenger-11.webp"
    ],
    "badge": null,
    "color": "#171717",
    "description": "2026墨西哥二客S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/229365502?uid=1"
  },
  {
    "id": "imported-mexico",
    "teamId": "mexico",
    "category": "Jerseys",
    "name": "Mexico Home Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-mexico-primary.webp",
    "gallery": [
      "/products/imported-mexico-primary.webp",
      "/products/imported-mexico-01.webp",
      "/products/imported-mexico-02.webp",
      "/products/imported-mexico-03.webp",
      "/products/imported-mexico-04.webp",
      "/products/imported-mexico-05.webp",
      "/products/imported-mexico-06.webp",
      "/products/imported-mexico-07.webp",
      "/products/imported-mexico-08.webp",
      "/products/imported-mexico-09.webp",
      "/products/imported-mexico-10.webp",
      "/products/imported-mexico-11.webp"
    ],
    "badge": null,
    "color": "#087b4b",
    "description": "2026墨西哥主场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/211334943?uid=1&isSubCate=false&referrercate=5063658"
  },
  {
    "id": "imported-netherlands-s-3xl",
    "teamId": "netherlands",
    "category": "Jerseys",
    "name": "Netherlands Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-netherlands-s-3xl-primary.webp",
    "gallery": [
      "/products/imported-netherlands-s-3xl-primary.webp",
      "/products/imported-netherlands-s-3xl-01.webp",
      "/products/imported-netherlands-s-3xl-02.webp",
      "/products/imported-netherlands-s-3xl-03.webp",
      "/products/imported-netherlands-s-3xl-04.webp",
      "/products/imported-netherlands-s-3xl-05.webp",
      "/products/imported-netherlands-s-3xl-06.webp",
      "/products/imported-netherlands-s-3xl-07.webp",
      "/products/imported-netherlands-s-3xl-08.webp",
      "/products/imported-netherlands-s-3xl-09.webp"
    ],
    "badge": null,
    "color": "#f36d21",
    "description": "2026荷兰客场S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/233710956?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  },
  {
    "id": "imported-netherlands-s-3xl-1",
    "teamId": "netherlands",
    "category": "Jerseys",
    "name": "Netherlands Home Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-netherlands-s-3xl-1-primary.webp",
    "gallery": [
      "/products/imported-netherlands-s-3xl-1-primary.webp",
      "/products/imported-netherlands-s-3xl-1-01.webp",
      "/products/imported-netherlands-s-3xl-1-02.webp",
      "/products/imported-netherlands-s-3xl-1-03.webp",
      "/products/imported-netherlands-s-3xl-1-04.webp",
      "/products/imported-netherlands-s-3xl-1-05.webp",
      "/products/imported-netherlands-s-3xl-1-06.webp",
      "/products/imported-netherlands-s-3xl-1-07.webp",
      "/products/imported-netherlands-s-3xl-1-08.webp",
      "/products/imported-netherlands-s-3xl-1-09.webp"
    ],
    "badge": null,
    "color": "#f36d21",
    "description": "2026荷兰主场S~3XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/233261206?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  },
  {
    "id": "imported-portugal",
    "teamId": "portugal",
    "category": "Jerseys",
    "name": "Portugal Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-portugal-primary.webp",
    "gallery": [
      "/products/imported-portugal-primary.webp",
      "/products/imported-portugal-01.webp",
      "/products/imported-portugal-02.webp",
      "/products/imported-portugal-03.webp",
      "/products/imported-portugal-04.webp",
      "/products/imported-portugal-05.webp",
      "/products/imported-portugal-06.webp",
      "/products/imported-portugal-07.webp",
      "/products/imported-portugal-08.webp",
      "/products/imported-portugal-09.webp"
    ],
    "badge": null,
    "color": "#ce1733",
    "description": "2026葡萄牙客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/219129307?uid=1"
  },
  {
    "id": "imported-portugal-1",
    "teamId": "portugal",
    "category": "Jerseys",
    "name": "Portugal Home Jersey 2025/26",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-portugal-1-primary.webp",
    "gallery": [
      "/products/imported-portugal-1-primary.webp",
      "/products/imported-portugal-1-01.webp",
      "/products/imported-portugal-1-02.webp",
      "/products/imported-portugal-1-03.webp",
      "/products/imported-portugal-1-04.webp",
      "/products/imported-portugal-1-05.webp",
      "/products/imported-portugal-1-06.webp",
      "/products/imported-portugal-1-07.webp",
      "/products/imported-portugal-1-08.webp",
      "/products/imported-portugal-1-09.webp"
    ],
    "badge": null,
    "color": "#ce1733",
    "description": "2526葡萄牙主场",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/185810892?uid=1"
  },
  {
    "id": "imported-spain",
    "teamId": "spain",
    "category": "Jerseys",
    "name": "Spain Away Jersey 2026",
    "price": 89,
    "oldPrice": null,
    "image": "/products/imported-spain-primary.webp",
    "gallery": [
      "/products/imported-spain-primary.webp",
      "/products/imported-spain-01.webp",
      "/products/imported-spain-02.webp",
      "/products/imported-spain-03.webp",
      "/products/imported-spain-04.webp",
      "/products/imported-spain-05.webp",
      "/products/imported-spain-06.webp",
      "/products/imported-spain-07.webp",
      "/products/imported-spain-08.webp",
      "/products/imported-spain-09.webp",
      "/products/imported-spain-10.webp",
      "/products/imported-spain-11.webp"
    ],
    "badge": null,
    "color": "#df2638",
    "description": "2026西班牙客场S~4XL",
    "sourceUrl": "https://yiben-sports.x.yupoo.com/albums/231652590?uid=1&isSubCate=false&referrercate=5063658&utm_source=copyLink"
  }
];
